# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jordan Bowman
email: desk@jrdnbwmn.com
description: >- # this means to ignore newlines until "baseurl:"
  Jordan Bowman makes stuff for the web and interviews entrepreneurs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jrdnbwmn.com" # the base hostname & protocol for your site, e.g. http://example.com
author: jrdnbwmn
twitter:
  username: jrdnbwmn
logo: /img/mug.jpg
social:
  name: Jordan Bowman
  links:
    - https://twitter.com/jrdnbwmn
    - https://plus.google.com/+JordanBowman
    - https://github.com/jrdnbwmn
    - https://medium.com/@jrdnbwmn
google_site_verification: ba0nqRhWolY1qsWZfe3v04Hymc3NtO_RpVJC_RcajLM
lang: en_US

twitter_username: jrdnbwmn
github_username: jrdnbwmn

# Posts
permalink: /:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap # Keep at end
jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: archive-date
    month: archive-date
    tag: archive-tag
  permalinks:
    year: '/year/:year/'
    month: '/month/:year-:month/'
    tag: '/tag/:name/'

# Other
timezone: America/Denver

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - pre-jekyll

# Keep these files safe
keep_files:
  - .git
  - .svn
  - .gitignore
